# Generated by Django 4.1.6 on 2023-02-09 12:06

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_primary_mobile_mainmodel_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
